#!/bin/sh

set -e

#USE_IDEA_DIR="${IDEA_PLUGIN_DIR:=${HOME}/Library/Application Support/IntelliJIdea2016.2}"
USE_SC_DIR="${SC_DIR:=/jjv/vbuild}"

echo "Rebuilding SC - installing into: $USE_SC_DIR"

cd ../../../
./bin/makeSC $USE_SC_DIR

cd $USE_SC_DIR
rm -rf bin
rm -rf StrataCode
unzip StrataCode.zip
mv StrataCode/bin bin

# The intelliJ plugin needs to add a reference to the sc.jar file for run configurations it manages.
# for now, it's finding it in the only place it knows it will be there - the plugin directory
# perhaps, when we create the intellij project, we should make a copy of the sc.jar file?  Or point it
# at the version of sc.jar that gets built from src in that intelliJ instance?

#echo "Installing IDEA plugin dir: $USE_IDEA_DIR"
#cp "${USE_SC_DIR}/bin/sc.jar" "${USE_IDEA_DIR}/sc4idea/lib/sc.jar"
#cp "${USE_SC_DIR}/bin/scrt-core-src.jar" "${USE_IDEA_DIR}/sc4idea/lib/scrt-core-src.jar"
