/*
 * Copyright (c) 2014. Jeffrey Vroom. All Rights Reserved.
 */

package sc.js;

import sc.obj.Constant;

/**
 * Used to represent a link to a URL in the system which is associated with a page type.
 * Generated by the @URL annotation, exposed via the LayeredSystem.buildInfo.getURLPaths() API.
 */
@JSSettings(jsLibFiles="js/tags.js", prefixAlias="sc_")
public class URLPath implements Comparable {
   /** The URL to use for this URLPath */
   @Constant
   public String url;

   /** Visible display name */
   @Constant
   public String name;

   /** Name to uniquely identify this URL path */
   @Constant
   public String keyName;

   /** Class, CFClass, or TypeDeclaration to represent the type of the page object for this URL */
   @Constant
   public Object pageType;

   public URLPath(String templatePathName, Object pageType) {
      keyName = templatePathName;
      name = templatePathName;
      this.pageType = pageType;

      // Turn /path/foo.html into path/foo as a display name
      if (name.startsWith("/"))
         name = name.substring(1);
      int lastSlashIx = name.lastIndexOf('/');
      if (lastSlashIx == -1)
         lastSlashIx = 0;
      int dotIx = name.indexOf('.', lastSlashIx);
      if (dotIx != -1)
         name = name.substring(0, dotIx);
      url = templatePathName;
   }

   public int hashCode() {
      return url.hashCode();
   }

   public boolean equals(Object other) {
      if (!(other instanceof URLPath))
         return false;
      URLPath op = (URLPath) other;

      return url.equals(op.url) && name.equals(op.name);
   }

   public String cleanURL(boolean expandIndex) {
      String res = url;
      if (res.equals("") && expandIndex)
         res = "index.html";
      if (res.startsWith("/"))
         res = res.substring(1);
      return res;
   }

   /** Cleans the first / and extension out of the URL and handles the default case */
   public static String getAppNameFromURL(String url) {
      String app = url;
      int ix = app.indexOf("/");
      if (ix != -1)
         app = app.substring(ix + 1);
      if (app.length() == 0)
         app = "index";
      ix = app.lastIndexOf(".");
      if (ix != -1)
         app = app.substring(0, ix);
      return app;
   }

   // TODO: this only works for the most rudimentary cases and should do escaping etc.
   public static String addQueryParam(String url, String param, String value) {
      if (url.contains("?"))
         url = url + "&" + param + "=" + value;
      else
         url = url + "?" + param + "=" + value;
      return url;
   }

   public String toString() {
      return name + ":" + url + " (key=" + keyName + ")";
   }

   public void convertToRelativePath() {
      if (url.startsWith("/") && url.length() > 1)
         url = url.substring(1);
   }

   public int compareTo(Object o) {
      if (!(o instanceof URLPath))
         return -1;
      return name.compareTo(((URLPath) o).name);
   }
}
